name: build app

on:
  push:

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: build docker image
          run: |
            docker build -t 1998/shehab/app1:01 .
            docker run 1998/shehab/app1:01
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}