name: build app

on:
  push:

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: build docker image
          run: docker build -t app1 .